# Generated by Django 3.2.8 on 2022-01-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(blank=True, upload_to='products/')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='products/')),
                ('videojc', models.FileField(blank=True, null=True, upload_to='products/', verbose_name='Video')),
                ('detail', models.TextField(max_length=300, verbose_name='Información del producto')),
                ('dimensiones', models.TextField(max_length=150, verbose_name='Dimensiones')),
                ('materiales', models.TextField(max_length=150, verbose_name='Materiales')),
                ('marked_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Original')),
                ('price', models.IntegerField()),
                ('warranty', models.CharField(blank=True, max_length=300, null=True, verbose_name='¿Garantia?')),
                ('linkjc', models.CharField(blank=True, max_length=300, null=True, verbose_name='URL')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='products/images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.product')),
            ],
        ),
    ]
